---
# Assert tasks file for ansible-role-ca-certificates

- name: "Test if CA Certificate Information is set correctly"
  ansible.builtin.assert:
    that:
      - certificate_file is defined
      - certificate_file is string
    quiet: yes
