---
# Install tasks file for ansible-role-ca-certificates

- name: "Upload Certificate to {{ inventory_hostname }}"
  ansible.builtin.copy:
    src: "{{ certificate_file }}"
    dest: "{{ ca_certificate_dir }}"
    mode: '0440'

- name: "Rename Certificate on {{ inventory_hostname }} (Debian)"
  ansible.builtin.shell:
    cmd: mv "{{ ca_certificate_dir }}/{{ certificate_file.split('/')[1] }}" "{{ ca_certificate_dir }}/{{ certificate_file.split('/')[1].rsplit('.', 1)[0] }}.crt"
  when:
    - ansible_facts['os_family'] == "Debian"

- name: "Call Shared CA Certificates Update tool on {{ inventory_hostname }}"
  ansible.builtin.shell:
    cmd: "{{ certificate_update_tool }}"
