---
# Install tasks file for ansible-role-certificates

- name: "Upload Certificate to {{ inventory_hostname }}"
  ansible.builtin.copy:
    src: "{{ certificate_file }}"
    dest: "{{ certificate_dir }}"
    mode: '0440'

#- debug:
#    msg: "{{ certificate_file.split('/')[1].rsplit('.', 1)[0] }}.crt"

- name: "Rename Certificate on {{ inventory_hostname }} (Debian)"
  ansible.builtin.shell:
    cmd: mv "{{ certificate_dir }}/{{ certificate_file.split('/')[1] }}" "{{ certificate_dir }}/{{ certificate_file.split('/')[1].rsplit('.', 1)[0] }}.crt"

- name: "Call Shared CA Certificates Update tool on {{ inventory_hostname }}"
  ansible.builtin.shell:
    cmd: "{{ certificate_update_tool }}"
